import { PlayersMap, LeagueRules, Team, MatchSchedule } from "../types";

// Player registry with unique IDs
export const INITIAL_PLAYERS: PlayersMap = {
  player_1: { id: "player_1", name: "Azeem Muhammad" },
  player_2: { id: "player_2", name: "Iqbal Qasim" },
  player_3: { id: "player_3", name: "Wasef" },
  player_4: { id: "player_4", name: "Qavi" },
  player_5: { id: "player_5", name: "Ikram" },
  player_6: { id: "player_6", name: "Sabih" },
  player_7: { id: "player_7", name: "Taha R" },
  player_8: { id: "player_8", name: "Anas" },
  player_9: { id: "player_9", name: "Junaid A" },
  player_10: { id: "player_10", name: "Qhyam" },
  player_11: { id: "player_11", name: "Adil" },
  player_12: { id: "player_12", name: "Fateh" },
  player_13: { id: "player_13", name: "Taha M" },
  player_14: { id: "player_14", name: "Shahrukh" },
  player_15: { id: "player_15", name: "Nasheet" },
  player_16: { id: "player_16", name: "Naseer" },
  player_17: { id: "player_17", name: "Junaid M" },
  player_18: { id: "player_18", name: "Saleem" },
  player_19: { id: "player_19", name: "Owais" },
  player_20: { id: "player_20", name: "MJ" },
  player_21: { id: "player_21", name: "Madni" },
  player_22: { id: "player_22", name: "Salman" },
  player_23: { id: "player_23", name: "Yasser" },
  player_24: { id: "player_24", name: "Fahad" },
  player_25: { id: "player_25", name: "Jabir Bhai" },
  player_26: { id: "player_26", name: "Yousaf" },
  player_27: { id: "player_27", name: "Zafar" },
  player_28: { id: "player_28", name: "Naveed" },
  player_29: { id: "player_29", name: "Javed C" },
  player_30: { id: "player_30", name: "Raza D" },
  player_31: { id: "player_31", name: "Rafey" },
  player_32: { id: "player_32", name: "Danial S" },
};

// Complete schedule of all 96 games
export const SEEDED_MATCHES: MatchSchedule[] = [
  {
    id: 1,
    teamA: "team1",
    pA1: "player_1",
    pA2: "player_8",
    teamB: "team3",
    pB1: "player_17",
    pB2: "player_24",
  },
  {
    id: 2,
    teamA: "team1",
    pA1: "player_2",
    pA2: "player_7",
    teamB: "team3",
    pB1: "player_18",
    pB2: "player_23",
  },
  {
    id: 3,
    teamA: "team1",
    pA1: "player_3",
    pA2: "player_6",
    teamB: "team3",
    pB1: "player_19",
    pB2: "player_22",
  },
  {
    id: 4,
    teamA: "team1",
    pA1: "player_4",
    pA2: "player_5",
    teamB: "team3",
    pB1: "player_20",
    pB2: "player_21",
  },
  {
    id: 5,
    teamA: "team1",
    pA1: "player_1",
    pA2: "player_7",
    teamB: "team4",
    pB1: "player_25",
    pB2: "player_32",
  },
  {
    id: 6,
    teamA: "team1",
    pA1: "player_8",
    pA2: "player_6",
    teamB: "team4",
    pB1: "player_26",
    pB2: "player_31",
  },
  {
    id: 7,
    teamA: "team1",
    pA1: "player_2",
    pA2: "player_5",
    teamB: "team4",
    pB1: "player_27",
    pB2: "player_30",
  },
  {
    id: 8,
    teamA: "team1",
    pA1: "player_3",
    pA2: "player_4",
    teamB: "team4",
    pB1: "player_28",
    pB2: "player_29",
  },
  {
    id: 9,
    teamA: "team2",
    pA1: "player_9",
    pA2: "player_16",
    teamB: "team4",
    pB1: "player_25",
    pB2: "player_31",
  },
  {
    id: 10,
    teamA: "team2",
    pA1: "player_10",
    pA2: "player_15",
    teamB: "team4",
    pB1: "player_32",
    pB2: "player_30",
  },
  {
    id: 11,
    teamA: "team2",
    pA1: "player_11",
    pA2: "player_14",
    teamB: "team4",
    pB1: "player_26",
    pB2: "player_29",
  },
  {
    id: 12,
    teamA: "team2",
    pA1: "player_12",
    pA2: "player_13",
    teamB: "team4",
    pB1: "player_27",
    pB2: "player_28",
  },
  {
    id: 13,
    teamA: "team2",
    pA1: "player_9",
    pA2: "player_15",
    teamB: "team3",
    pB1: "player_17",
    pB2: "player_23",
  },
  {
    id: 14,
    teamA: "team2",
    pA1: "player_16",
    pA2: "player_14",
    teamB: "team3",
    pB1: "player_24",
    pB2: "player_22",
  },
  {
    id: 15,
    teamA: "team2",
    pA1: "player_10",
    pA2: "player_13",
    teamB: "team3",
    pB1: "player_18",
    pB2: "player_21",
  },
  {
    id: 16,
    teamA: "team2",
    pA1: "player_11",
    pA2: "player_12",
    teamB: "team3",
    pB1: "player_19",
    pB2: "player_20",
  },
  {
    id: 17,
    teamA: "team1",
    pA1: "player_1",
    pA2: "player_6",
    teamB: "team2",
    pB1: "player_9",
    pB2: "player_14",
  },
  {
    id: 18,
    teamA: "team1",
    pA1: "player_7",
    pA2: "player_5",
    teamB: "team2",
    pB1: "player_15",
    pB2: "player_13",
  },
  {
    id: 19,
    teamA: "team1",
    pA1: "player_8",
    pA2: "player_4",
    teamB: "team2",
    pB1: "player_16",
    pB2: "player_12",
  },
  {
    id: 20,
    teamA: "team1",
    pA1: "player_2",
    pA2: "player_3",
    teamB: "team2",
    pB1: "player_10",
    pB2: "player_11",
  },
  {
    id: 21,
    teamA: "team3",
    pA1: "player_17",
    pA2: "player_22",
    teamB: "team4",
    pB1: "player_25",
    pB2: "player_30",
  },
  {
    id: 22,
    teamA: "team3",
    pA1: "player_23",
    pA2: "player_21",
    teamB: "team4",
    pB1: "player_31",
    pB2: "player_29",
  },
  {
    id: 23,
    teamA: "team3",
    pA1: "player_24",
    pA2: "player_20",
    teamB: "team4",
    pB1: "player_32",
    pB2: "player_28",
  },
  {
    id: 24,
    teamA: "team3",
    pA1: "player_18",
    pA2: "player_19",
    teamB: "team4",
    pB1: "player_26",
    pB2: "player_27",
  },
  {
    id: 25,
    teamA: "team2",
    pA1: "player_9",
    pA2: "player_13",
    teamB: "team4",
    pB1: "player_25",
    pB2: "player_29",
  },
  {
    id: 26,
    teamA: "team2",
    pA1: "player_14",
    pA2: "player_12",
    teamB: "team4",
    pB1: "player_30",
    pB2: "player_28",
  },
  {
    id: 27,
    teamA: "team2",
    pA1: "player_15",
    pA2: "player_11",
    teamB: "team4",
    pB1: "player_31",
    pB2: "player_27",
  },
  {
    id: 28,
    teamA: "team2",
    pA1: "player_16",
    pA2: "player_10",
    teamB: "team4",
    pB1: "player_32",
    pB2: "player_26",
  },
  {
    id: 29,
    teamA: "team1",
    pA1: "player_1",
    pA2: "player_5",
    teamB: "team3",
    pB1: "player_17",
    pB2: "player_21",
  },
  {
    id: 30,
    teamA: "team1",
    pA1: "player_6",
    pA2: "player_4",
    teamB: "team3",
    pB1: "player_22",
    pB2: "player_20",
  },
  {
    id: 31,
    teamA: "team1",
    pA1: "player_7",
    pA2: "player_3",
    teamB: "team3",
    pB1: "player_23",
    pB2: "player_19",
  },
  {
    id: 32,
    teamA: "team1",
    pA1: "player_8",
    pA2: "player_2",
    teamB: "team3",
    pB1: "player_24",
    pB2: "player_18",
  },
  {
    id: 33,
    teamA: "team1",
    pA1: "player_1",
    pA2: "player_4",
    teamB: "team2",
    pB1: "player_9",
    pB2: "player_12",
  },
  {
    id: 34,
    teamA: "team1",
    pA1: "player_5",
    pA2: "player_3",
    teamB: "team2",
    pB1: "player_13",
    pB2: "player_11",
  },
  {
    id: 35,
    teamA: "team1",
    pA1: "player_6",
    pA2: "player_2",
    teamB: "team2",
    pB1: "player_14",
    pB2: "player_10",
  },
  {
    id: 36,
    teamA: "team1",
    pA1: "player_7",
    pA2: "player_8",
    teamB: "team2",
    pB1: "player_15",
    pB2: "player_16",
  },
  {
    id: 37,
    teamA: "team2",
    pA1: "player_9",
    pA2: "player_11",
    teamB: "team3",
    pB1: "player_17",
    pB2: "player_20",
  },
  {
    id: 38,
    teamA: "team2",
    pA1: "player_12",
    pA2: "player_10",
    teamB: "team3",
    pB1: "player_21",
    pB2: "player_19",
  },
  {
    id: 39,
    teamA: "team2",
    pA1: "player_13",
    pA2: "player_16",
    teamB: "team3",
    pB1: "player_22",
    pB2: "player_18",
  },
  {
    id: 40,
    teamA: "team2",
    pA1: "player_14",
    pA2: "player_15",
    teamB: "team3",
    pB1: "player_23",
    pB2: "player_24",
  },
  {
    id: 41,
    teamA: "team1",
    pA1: "player_1",
    pA2: "player_3",
    teamB: "team4",
    pB1: "player_25",
    pB2: "player_28",
  },
  {
    id: 42,
    teamA: "team1",
    pA1: "player_4",
    pA2: "player_2",
    teamB: "team4",
    pB1: "player_29",
    pB2: "player_27",
  },
  {
    id: 43,
    teamA: "team1",
    pA1: "player_5",
    pA2: "player_8",
    teamB: "team4",
    pB1: "player_30",
    pB2: "player_26",
  },
  {
    id: 44,
    teamA: "team1",
    pA1: "player_6",
    pA2: "player_7",
    teamB: "team4",
    pB1: "player_31",
    pB2: "player_32",
  },
  {
    id: 45,
    teamA: "team3",
    pA1: "player_17",
    pA2: "player_19",
    teamB: "team4",
    pB1: "player_25",
    pB2: "player_27",
  },
  {
    id: 46,
    teamA: "team3",
    pA1: "player_20",
    pA2: "player_18",
    teamB: "team4",
    pB1: "player_28",
    pB2: "player_26",
  },
  {
    id: 47,
    teamA: "team3",
    pA1: "player_21",
    pA2: "player_24",
    teamB: "team4",
    pB1: "player_29",
    pB2: "player_32",
  },
  {
    id: 48,
    teamA: "team3",
    pA1: "player_22",
    pA2: "player_23",
    teamB: "team4",
    pB1: "player_30",
    pB2: "player_31",
  },
  {
    id: 49,
    teamA: "team1",
    pA1: "player_1",
    pA2: "player_2",
    teamB: "team4",
    pB1: "player_25",
    pB2: "player_26",
  },
  {
    id: 50,
    teamA: "team1",
    pA1: "player_3",
    pA2: "player_8",
    teamB: "team4",
    pB1: "player_27",
    pB2: "player_32",
  },
  {
    id: 51,
    teamA: "team1",
    pA1: "player_4",
    pA2: "player_7",
    teamB: "team4",
    pB1: "player_28",
    pB2: "player_31",
  },
  {
    id: 52,
    teamA: "team1",
    pA1: "player_5",
    pA2: "player_6",
    teamB: "team4",
    pB1: "player_29",
    pB2: "player_30",
  },
  {
    id: 53,
    teamA: "team1",
    pA1: "player_1",
    pA2: "player_8",
    teamB: "team2",
    pB1: "player_9",
    pB2: "player_10",
  },
  {
    id: 54,
    teamA: "team1",
    pA1: "player_2",
    pA2: "player_7",
    teamB: "team2",
    pB1: "player_11",
    pB2: "player_16",
  },
  {
    id: 55,
    teamA: "team1",
    pA1: "player_3",
    pA2: "player_6",
    teamB: "team2",
    pB1: "player_12",
    pB2: "player_15",
  },
  {
    id: 56,
    teamA: "team1",
    pA1: "player_4",
    pA2: "player_5",
    teamB: "team2",
    pB1: "player_13",
    pB2: "player_14",
  },
  {
    id: 57,
    teamA: "team2",
    pA1: "player_9",
    pA2: "player_16",
    teamB: "team3",
    pB1: "player_17",
    pB2: "player_18",
  },
  {
    id: 58,
    teamA: "team2",
    pA1: "player_10",
    pA2: "player_15",
    teamB: "team3",
    pB1: "player_19",
    pB2: "player_24",
  },
  {
    id: 59,
    teamA: "team2",
    pA1: "player_11",
    pA2: "player_14",
    teamB: "team3",
    pB1: "player_20",
    pB2: "player_23",
  },
  {
    id: 60,
    teamA: "team2",
    pA1: "player_12",
    pA2: "player_13",
    teamB: "team3",
    pB1: "player_21",
    pB2: "player_22",
  },
  {
    id: 61,
    teamA: "team2",
    pA1: "player_9",
    pA2: "player_15",
    teamB: "team4",
    pB1: "player_25",
    pB2: "player_32",
  },
  {
    id: 62,
    teamA: "team2",
    pA1: "player_16",
    pA2: "player_14",
    teamB: "team4",
    pB1: "player_26",
    pB2: "player_31",
  },
  {
    id: 63,
    teamA: "team2",
    pA1: "player_10",
    pA2: "player_13",
    teamB: "team4",
    pB1: "player_27",
    pB2: "player_30",
  },
  {
    id: 64,
    teamA: "team2",
    pA1: "player_11",
    pA2: "player_12",
    teamB: "team4",
    pB1: "player_28",
    pB2: "player_29",
  },
  {
    id: 65,
    teamA: "team3",
    pA1: "player_17",
    pA2: "player_24",
    teamB: "team4",
    pB1: "player_25",
    pB2: "player_31",
  },
  {
    id: 66,
    teamA: "team3",
    pA1: "player_18",
    pA2: "player_23",
    teamB: "team4",
    pB1: "player_32",
    pB2: "player_30",
  },
  {
    id: 67,
    teamA: "team3",
    pA1: "player_19",
    pA2: "player_22",
    teamB: "team4",
    pB1: "player_26",
    pB2: "player_29",
  },
  {
    id: 68,
    teamA: "team3",
    pA1: "player_20",
    pA2: "player_21",
    teamB: "team4",
    pB1: "player_27",
    pB2: "player_28",
  },
  {
    id: 69,
    teamA: "team1",
    pA1: "player_1",
    pA2: "player_7",
    teamB: "team3",
    pB1: "player_17",
    pB2: "player_23",
  },
  {
    id: 70,
    teamA: "team1",
    pA1: "player_8",
    pA2: "player_6",
    teamB: "team3",
    pB1: "player_24",
    pB2: "player_22",
  },
  {
    id: 71,
    teamA: "team1",
    pA1: "player_2",
    pA2: "player_5",
    teamB: "team3",
    pB1: "player_18",
    pB2: "player_21",
  },
  {
    id: 72,
    teamA: "team1",
    pA1: "player_3",
    pA2: "player_4",
    teamB: "team3",
    pB1: "player_19",
    pB2: "player_20",
  },
  {
    id: 73,
    teamA: "team2",
    pA1: "player_9",
    pA2: "player_14",
    teamB: "team3",
    pB1: "player_17",
    pB2: "player_22",
  },
  {
    id: 74,
    teamA: "team2",
    pA1: "player_15",
    pA2: "player_13",
    teamB: "team3",
    pB1: "player_23",
    pB2: "player_21",
  },
  {
    id: 75,
    teamA: "team2",
    pA1: "player_16",
    pA2: "player_12",
    teamB: "team3",
    pB1: "player_24",
    pB2: "player_20",
  },
  {
    id: 76,
    teamA: "team2",
    pA1: "player_10",
    pA2: "player_11",
    teamB: "team3",
    pB1: "player_18",
    pB2: "player_19",
  },
  {
    id: 77,
    teamA: "team1",
    pA1: "player_1",
    pA2: "player_6",
    teamB: "team3",
    pB1: "player_17",
    pB2: "player_21",
  },
  {
    id: 78,
    teamA: "team1",
    pA1: "player_7",
    pA2: "player_5",
    teamB: "team3",
    pB1: "player_22",
    pB2: "player_20",
  },
  {
    id: 79,
    teamA: "team1",
    pA1: "player_8",
    pA2: "player_4",
    teamB: "team3",
    pB1: "player_23",
    pB2: "player_19",
  },
  {
    id: 80,
    teamA: "team1",
    pA1: "player_2",
    pA2: "player_3",
    teamB: "team3",
    pB1: "player_24",
    pB2: "player_18",
  },
  {
    id: 81,
    teamA: "team1",
    pA1: "player_1",
    pA2: "player_5",
    teamB: "team4",
    pB1: "player_25",
    pB2: "player_30",
  },
  {
    id: 82,
    teamA: "team1",
    pA1: "player_6",
    pA2: "player_4",
    teamB: "team4",
    pB1: "player_31",
    pB2: "player_29",
  },
  {
    id: 83,
    teamA: "team1",
    pA1: "player_7",
    pA2: "player_3",
    teamB: "team4",
    pB1: "player_32",
    pB2: "player_28",
  },
  {
    id: 84,
    teamA: "team1",
    pA1: "player_8",
    pA2: "player_2",
    teamB: "team4",
    pB1: "player_26",
    pB2: "player_27",
  },
  {
    id: 85,
    teamA: "team3",
    pA1: "player_17",
    pA2: "player_20",
    teamB: "team4",
    pB1: "player_25",
    pB2: "player_29",
  },
  {
    id: 86,
    teamA: "team3",
    pA1: "player_21",
    pA2: "player_19",
    teamB: "team4",
    pB1: "player_30",
    pB2: "player_28",
  },
  {
    id: 87,
    teamA: "team3",
    pA1: "player_22",
    pA2: "player_18",
    teamB: "team4",
    pB1: "player_31",
    pB2: "player_27",
  },
  {
    id: 88,
    teamA: "team3",
    pA1: "player_23",
    pA2: "player_24",
    teamB: "team4",
    pB1: "player_32",
    pB2: "player_26",
  },
  {
    id: 89,
    teamA: "team1",
    pA1: "player_1",
    pA2: "player_4",
    teamB: "team2",
    pB1: "player_9",
    pB2: "player_13",
  },
  {
    id: 90,
    teamA: "team1",
    pA1: "player_5",
    pA2: "player_3",
    teamB: "team2",
    pB1: "player_14",
    pB2: "player_12",
  },
  {
    id: 91,
    teamA: "team1",
    pA1: "player_6",
    pA2: "player_2",
    teamB: "team2",
    pB1: "player_15",
    pB2: "player_11",
  },
  {
    id: 92,
    teamA: "team1",
    pA1: "player_7",
    pA2: "player_8",
    teamB: "team2",
    pB1: "player_16",
    pB2: "player_10",
  },
  {
    id: 93,
    teamA: "team2",
    pA1: "player_9",
    pA2: "player_12",
    teamB: "team4",
    pB1: "player_25",
    pB2: "player_28",
  },
  {
    id: 94,
    teamA: "team2",
    pA1: "player_13",
    pA2: "player_11",
    teamB: "team4",
    pB1: "player_29",
    pB2: "player_27",
  },
  {
    id: 95,
    teamA: "team2",
    pA1: "player_14",
    pA2: "player_10",
    teamB: "team4",
    pB1: "player_30",
    pB2: "player_26",
  },
  {
    id: 96,
    teamA: "team2",
    pA1: "player_15",
    pA2: "player_16",
    teamB: "team4",
    pB1: "player_31",
    pB2: "player_32",
  },
];

export const LEAGUE_RULES: LeagueRules = {
  totalGames: 96,
  flexLimit: 10,
};

export const INITIAL_TEAMS: Team[] = [
  {
    id: "team1",
    name: "Naan-Stop Picklers",
    captain: "player_1",
    players: [
      "player_1",
      "player_2",
      "player_3",
      "player_4",
      "player_5",
      "player_6",
      "player_7",
      "player_8",
    ],
    color: "from-blue-500 to-cyan-400",
    logo: "/logos/naan-stop-picklers.png",
  },
  {
    id: "team2",
    name: "Striking Falcons",
    captain: "player_9",
    players: [
      "player_9",
      "player_10",
      "player_11",
      "player_12",
      "player_13",
      "player_14",
      "player_15",
      "player_16",
    ],
    color: "from-red-500 to-orange-400",
    logo: "/logos/striking-falcons.png",
  },
  {
    id: "team3",
    name: "Pickle Warriors",
    captain: "player_17",
    players: [
      "player_17",
      "player_18",
      "player_19",
      "player_20",
      "player_21",
      "player_22",
      "player_23",
      "player_24",
    ],
    color: "from-emerald-500 to-lime-400",
    logo: "/logos/pickle-warriors.png",
  },
  {
    id: "team4",
    name: "BadMashers",
    captain: "player_25",
    players: [
      "player_25",
      "player_26",
      "player_27",
      "player_28",
      "player_29",
      "player_30",
      "player_31",
      "player_32",
    ],
    color: "from-purple-500 to-pink-400",
    logo: "/logos/badmashers.png",
  },
];
